### ISSUE TITLE
Crashes when deploying to Heroku

### ISSUE THREAD

**Issue by ghoople** [networked-aframe/naf-easyrtc-adapter#8]
I'm stuck when deploying to Heroku. I click the "Deploy to Heroku" button in the tutorial. The app looks to install correctly, however upon launching it crashes. I'm very new to all this so may be a mistake on my end, but its not obvious where I've gone wrong. (Thanks for developing this, its awesome!)  

Heroku Application Log: 

2020-11-21T00:15:04.183959+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
2020-11-21T00:15:04.183960+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
2020-11-21T00:15:04.183960+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:879:32)
2020-11-21T00:15:04.183961+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-11-21T00:15:04.183962+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2020-11-21T00:15:04.183962+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2020-11-21T00:15:04.183963+00:00 app[web.1]:   requireStack: [ '/app/server/index.js' ]
2020-11-21T00:15:04.183963+00:00 app[web.1]: }
2020-11-21T00:15:04.267621+00:00 heroku[web.1]: Process exited with status 1
2020-11-21T00:15:04.430984+00:00 heroku[web.1]: State changed from starting to crashed

(I manually restarted all dynos here) 

2020-11-21T00:22:44.035582+00:00 heroku[web.1]: State changed from crashed to starting
2020-11-21T00:22:47.163946+00:00 heroku[web.1]: Starting process with command `node server/index.js`
2020-11-21T00:22:49.762919+00:00 heroku[web.1]: Process exited with status 1
2020-11-21T00:22:49.805578+00:00 heroku[web.1]: State changed from starting to crashed
2020-11-21T00:22:49.714414+00:00 app[web.1]: internal/modules/cjs/loader.js:834
2020-11-21T00:22:49.714464+00:00 app[web.1]:   throw err;
2020-11-21T00:22:49.714465+00:00 app[web.1]:   ^
2020-11-21T00:22:49.714466+00:00 app[web.1]: 
2020-11-21T00:22:49.714466+00:00 app[web.1]: Error: Cannot find module 'socket.io'
2020-11-21T00:22:49.714466+00:00 app[web.1]: Require stack:
2020-11-21T00:22:49.714467+00:00 app[web.1]: - /app/server/index.js
2020-11-21T00:22:49.719268+00:00 app[web.1]:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:831:15)
2020-11-21T00:22:49.719274+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
2020-11-21T00:22:49.719275+00:00 app[web.1]:     at Module.require (internal/modules/cjs/loader.js:903:19)
2020-11-21T00:22:49.719276+00:00 app[web.1]:     at require (internal/modules/cjs/helpers.js:74:18)
2020-11-21T00:22:49.719276+00:00 app[web.1]:     at Object.<anonymous> (/app/server/index.js:5:16)
2020-11-21T00:22:49.719276+00:00 app[web.1]:     at Module._compile (internal/modules/cjs/loader.js:1015:30)
2020-11-21T00:22:49.719277+00:00 app[web.1]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1035:10)
2020-11-21T00:22:49.719277+00:00 app[web.1]:     at Module.load (internal/modules/cjs/loader.js:879:32)
2020-11-21T00:22:49.719278+00:00 app[web.1]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
2020-11-21T00:22:49.719293+00:00 app[web.1]:     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
2020-11-21T00:22:49.719294+00:00 app[web.1]:   code: 'MODULE_NOT_FOUND',
2020-11-21T00:22:49.719295+00:00 app[web.1]:   requireStack: [ '/app/server/index.js' ]
2020-11-21T00:22:49.719295+00:00 app[web.1]: }

For reference here is the Heroku Build Log: 
[build-log.txt](https://github.com/networked-aframe/naf-easyrtc-adapter/files/5576715/build-log.txt)

**Comment by ghoople** [comment]
see forked version for solution from hthetiot

**Comment by vincentfretin** [comment]
I don't know heroku deployment. Why doesn't it find the socket.io dependency here? Did you fix the issue since then?

**Comment by vincentfretin** [comment]
The easyrtc adapter moved again to the networked-aframe repository. I'm closing all issues in this repository.
